name: Run accesibility (a11y) tests
description: "Runs accesibility (a11y) tests for a set of urls"
inputs:
  urls:
    description: "The separated comma list of urls the tests should be executed against"
    required: true
    default: ""
  fail-on-error:
    description: "If true the action will fail if an error is found"
    required: false
    default: true
  install:
    description: "Whether or not to run install"
    required: false
    default: false
  start-command:
    description: "Command for starting local server in the background"
    required: false
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.urls }}
    - ${{ inputs.fail-on-error }}
    - ${{ inputs.install }}
    - ${{ inputs.start-command }}
