name: Run accesibility (a11y) tests
description: "Runs accesibility (a11y) tests for a set of urls"
inputs:
  urls:
    description: "The separated comma list of urls the tests should be executed against"
    required: true
    default: ""
  fail-on-error:
    description: "If true the action will fail if an error is found"
    required: false
    default: true
  wait-on:
    description: "The url we need to wait to run the tests against"
    required: false
    default: ""
  wait-on-timeout:
    description: "The amount of seconds we need to wait until the site is started"
    required: false
    default: 60
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.urls }}
    - ${{ inputs.fail-on-error }}
    - ${{ inputs.wait-on }}
    - ${{ inputs.wait-on-timeout }}
